server:
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, alias

      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowCredentials: true
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods: "*"
#            maxAge: 3628800



dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848